In [6]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([1.0, 2.0, 3.0])
c = np.zeros((2, 3))
d = np.ones((3, 2))
e = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
f = np.linspace(0, 1, 5) 
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
X = np.array([
	[1.0, 10.0, 100.0],
	[2.0, 20.0, 200.0],
	[3.0, 30.0, 300.0],
])

media = X.mean(axis=0)
X_centrada = X - media

print(media)
print(X_centrada)

[  2.  20. 200.]
[[  -1.  -10. -100.]
 [   0.    0.    0.]
 [   1.   10.  100.]]


In [9]:
Z = np.array([
	[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]
])

print(Z.sum())          # suma total
print(Z.sum(axis=0))    # suma por columna
print(Z.sum(axis=1))    # suma por fila
print(Z.mean(axis=0))

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


In [10]:
arr = np.array([1.0, np.nan, 3.5, np.nan, 5.0])

print(np.isnan(arr))
print(np.nanmean(arr))

arr_filled = np.where(np.isnan(arr), np.nanmean(arr), arr)
print(arr_filled)

[False  True False  True False]
3.1666666666666665
[1.         3.16666667 3.5        3.16666667 5.        ]


In [19]:


# Crear datos de estudiantes con ID, nombre y exámenes
data = {
    'ID': list(range(1, 11)),
    'Nombre': [f'Estudiante{i}' for i in range(1, 11)],
    'Examen1': np.random.randint(0, 101, 10),
    'Examen2': np.random.randint(0, 101, 10),
    'Examen3': np.random.randint(0, 101, 10)
}

df = pd.DataFrame(data)

# Guardar como CSV
df.to_csv('estudiantes.csv', index=False)

print("CSV creado: estudiantes.csv")
print(df)

CSV creado: estudiantes.csv
   ID        Nombre  Examen1  Examen2  Examen3
0   1   Estudiante1       99       26       33
1   2   Estudiante2       94       34        6
2   3   Estudiante3       26       87        5
3   4   Estudiante4       22       62       59
4   5   Estudiante5       69       87       48
5   6   Estudiante6        0       56       15
6   7   Estudiante7       67       74       76
7   8   Estudiante8        3       21       27
8   9   Estudiante9       50       70       11
9  10  Estudiante10       27        9       55


In [18]:
import pandas as pd

df = pd.read_csv("estudiantes.csv")

print(df.shape)
print(df.head())
print(df.info())
print(df.describe(include="all"))

(10, 5)
   ID       Nombre  Examen1  Examen2  Examen3
0   1  Estudiante1       37       91        9
1   2  Estudiante2       75       38       77
2   3  Estudiante3        6       30       65
3   4  Estudiante4        4       12       49
4   5  Estudiante5       74       41       69
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       10 non-null     int64
 1   Nombre   10 non-null     str  
 2   Examen1  10 non-null     int64
 3   Examen2  10 non-null     int64
 4   Examen3  10 non-null     int64
dtypes: int64(4), str(1)
memory usage: 532.0 bytes
None
              ID       Nombre     Examen1    Examen2    Examen3
count   10.00000           10   10.000000  10.000000  10.000000
unique       NaN           10         NaN        NaN        NaN
top          NaN  Estudiante1         NaN        NaN        NaN
freq         NaN            1         NaN        NaN        Na

In [ ]:
# Ordenamiento con Pandas

# Cargar el DataFrame si no está en memoria
import pandas as pd
df = pd.read_csv("estudiantes.csv")

# Ordenar por una columna (por ejemplo, Examen1 ascendente)
df_sorted = df.sort_values('Examen1')
print("Ordenado por Examen1:")
print(df_sorted)

# Ordenar por múltiples columnas (Examen1 ascendente, Examen2 descendente)
df_sorted_multi = df.sort_values(['Examen1', 'Examen2'], ascending=[True, False])
print("\nOrdenado por Examen1 asc, Examen2 desc:")
print(df_sorted_multi)



Ordenado por Examen1:
   ID        Nombre  Examen1  Examen2  Examen3
5   6   Estudiante6        0       56       15
7   8   Estudiante8        3       21       27
3   4   Estudiante4       22       62       59
2   3   Estudiante3       26       87        5
9  10  Estudiante10       27        9       55
8   9   Estudiante9       50       70       11
6   7   Estudiante7       67       74       76
4   5   Estudiante5       69       87       48
1   2   Estudiante2       94       34        6
0   1   Estudiante1       99       26       33

Ordenado por Examen1 asc, Examen2 desc:
   ID        Nombre  Examen1  Examen2  Examen3
5   6   Estudiante6        0       56       15
7   8   Estudiante8        3       21       27
3   4   Estudiante4       22       62       59
2   3   Estudiante3       26       87        5
9  10  Estudiante10       27        9       55
8   9   Estudiante9       50       70       11
6   7   Estudiante7       67       74       76
4   5   Estudiante5       69       87       

In [24]:
# Ordenar por índice
df_sorted_index = df.sort_index()
print("\nOrdenado por índice:")
print(df_sorted_index)


Ordenado por índice:
   ID        Nombre  Examen1  Examen2  Examen3
0   1   Estudiante1       99       26       33
1   2   Estudiante2       94       34        6
2   3   Estudiante3       26       87        5
3   4   Estudiante4       22       62       59
4   5   Estudiante5       69       87       48
5   6   Estudiante6        0       56       15
6   7   Estudiante7       67       74       76
7   8   Estudiante8        3       21       27
8   9   Estudiante9       50       70       11
9  10  Estudiante10       27        9       55


In [25]:
clientes = pd.DataFrame({
	"id": [1, 2, 3],
	"ciudad": ["La Paz", "Cochabamba", "Santa Cruz"]
})

compras = pd.DataFrame({
	"id": [1, 1, 2, 4],
	"monto": [100, 80, 120, 50]
})

left_merge = clientes.merge(compras, on="id", how="left")
inner_merge = clientes.merge(compras, on="id", how="inner")

print(left_merge)
print(inner_merge)

   id      ciudad  monto
0   1      La Paz  100.0
1   1      La Paz   80.0
2   2  Cochabamba  120.0
3   3  Santa Cruz    NaN
   id      ciudad  monto
0   1      La Paz    100
1   1      La Paz     80
2   2  Cochabamba    120


In [26]:
# Explicación de sort_index()
import pandas as pd
df = pd.read_csv("estudiantes.csv")

# Después de ordenar por valores, el índice queda desordenado
df_sorted = df.sort_values('Examen1')
print("Después de sort_values('Examen1'), el índice queda:")
print(df_sorted.index.tolist())  # Ejemplo: [5, 7, 3, 2, 9, 8, 6, 4, 1, 0]

# sort_index() reordena las filas según el índice
df_back = df_sorted.sort_index()
print("\nDespués de sort_index(), el índice vuelve a:")
print(df_back.index.tolist())  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print("\nDataFrame original:")
print(df_back)

Después de sort_values('Examen1'), el índice queda:
[5, 7, 3, 2, 9, 8, 6, 4, 1, 0]

Después de sort_index(), el índice vuelve a:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

DataFrame original:
   ID        Nombre  Examen1  Examen2  Examen3
0   1   Estudiante1       99       26       33
1   2   Estudiante2       94       34        6
2   3   Estudiante3       26       87        5
3   4   Estudiante4       22       62       59
4   5   Estudiante5       69       87       48
5   6   Estudiante6        0       56       15
6   7   Estudiante7       67       74       76
7   8   Estudiante8        3       21       27
8   9   Estudiante9       50       70       11
9  10  Estudiante10       27        9       55
